package com.approvalflow.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * Represents an approval request stored in the "requests" MongoDB collection.
 *
 * Lifecycle:
 *   1. An EMPLOYEE submits a request  → status = PENDING
 *   2. A MANAGER reviews it           → status = APPROVED | REJECTED
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "requests")
public class ApprovalRequest {

    /** Unique identifier for this request (auto-generated by MongoDB). */
    @Id
    private String requestId;

    /** A short description of what is being requested. */
    private String description;

    /**
     * Current status of the request.
     * Defaults to PENDING when first created (set in the service layer).
     */
    private RequestStatus status;

    /** The userId of the employee who created this request. */
    private String employeeId;

    /**
     * The userId of the manager who acted on this request.
     * Null until a manager approves or rejects it.
     */
    private String managerId;

    /** Timestamp when the request was first created. */
    private LocalDateTime createdAt;
}
